seed: 42
train:
  epochs: 100
  learning_rate: 0.003
  optimizer: "adam"
  scheduler: "StepLR"
  step_size: 20
  gamma: 0.1
  weight_decay: 0
  checkpoint_dir: "checkpoints"
  benchmark: True
  deterministic: True
  accelerator: "gpu"
  devices: [0]
  strategy: "DDP"
  precision: 32
  accumulate_grad_batches: 1
  fast_dev_run: False
  pretrain_file: None
dataset:
  hdf5_path: "h5/upper.hdf5"
dataloader:
  batch_size: 8
  num_workers: 2
model:
  name: "iMeshSegNet"
  num_classes: 15 #TeethLabels + 1(gum)
  num_channels: 15
  with_dropout: True
  dropout_p: 0.5
logger:
  name: 'wandb'
  use: True
  project: "iMeshSegNet"
  log_every_n_steps: 5
